apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: marketPlace-deployment
  labels:
    app: marketPlace
spec:
  template:
    metadata:
      labels:
        app: marketPlace
    spec:
      containers:
        - name: mp-microservice-akka
          image: gcr.io/heroic-alpha-195822/a2censo-estadisticas
          ports:
            - containerPort: 5000
          env:
            - name: A2CENSO_DB_HOST
              value: 127.0.0.1:3306
            # These secrets are required to start the pod.
            # [START cloudsql_secrets]
            - name: A2CENSO_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: A2CENSO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            # [END cloudsql_secrets]
        # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
        # project, the region of your Cloud SQL instance and the name
        # of your Cloud SQL instance. The format is
        # $PROJECT:$REGION:$INSTANCE
        # [START proxy_container]
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=heroic-alpha-195822:us-central1:a2censo=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
      # [END volumes]
---
apiVersion: v1
kind: Service
metadata:
  name: mp-microservice-akka-service
spec:
  type: LoadBalancer
  selector:
    app: marketPlace
    tier: backend
    serves: http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000