apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mplace-micservice-deployment
spec:
  replicas: 3 # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: marketplace
        tier: backend
        stack: akka
        serves: http
    spec:
      containers:
      - name: mp-microservice-akka
        image: gcr.io/heroic-alpha-195822/a2censoapplication:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: 127.0.0.1:3306
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=market-place-a2censo:us-central1:a2censo=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      # [END proxy_container]
    # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
---
apiVersion: v1
kind: Service
metadata:
  name: mplace-micservice-service
spec:
  type: LoadBalancer
  selector:
    app: refel
    tier: backend
    serves: http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000